### ISSUE TITLE
Goerli support

### ISSUE THREAD

**Issue by drLis** [smartcontractkit/chainlink-mix#49]
Now we have hainlick at Goerli and Kovan/Ropsten are deprecated, so should we add goerli params to config?

It will be very uesfull. I used these for API calls:
```
goerli:
        eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
        fee: 100000000000000000
        fund_amount: 5000000000000000000
        gas_lane: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
        jobId: 7223acbd01654282865b678924126013
        keyhash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
        link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
        oracle: "0xCC79157eb46F5624204f47AB42b3906cAA40eaB7"
        # Add your sub_id
        # subscription_id: 1003
        verify: true
        vrf_coordinator: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D"
```
